import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('bn')];

  static const _en = <String, String>{
    'appName': 'LinguaLens',
    'appTagline': 'A calmer way to teach',
    'welcome': 'Welcome back, teacher',
    'dashboard': 'Dashboard',
    'students': 'Students',
    'batches': 'Batches',
    'attendance': 'Attendance',
    'today': 'Today',
    'previousDay': 'Previous day',
    'nextDay': 'Next day',
    'markAttendance': 'Mark attendance',
    'saveAttendance': 'Save attendance',
    'attendanceSaved': 'Attendance saved',
    'attendanceCalendar': 'Attendance calendar',
    'attendanceNote': 'Attendance note',
    'saveNote': 'Save note',
    'clearNote': 'Clear note',
    'present': 'Present',
    'absent': 'Absent',
    'late': 'Late',
    'leave': 'Leave',
    'unmarked': 'Unmarked',
    'expected': 'Expected',
    'marked': 'Marked',
    'noActiveBatches': 'No active batches',
    'createBatchToMarkAttendance':
        'Create a batch and enroll students to mark attendance',
    'noEligibleStudents': 'No eligible students for this date',
    'noStudentsForAttendance': 'No students available for attendance',
    'enrollStudentsFirst': 'Enroll students in this batch first',
    'markAllPresent': 'Mark all present',
    'clearAll': 'Clear all',
    'archivedBatchInfo': 'This batch is archived',
    'noAttendanceRecordsYet': 'No attendance records yet',
    'attendanceWillAppear': 'Attendance will appear here after marking',
    'noAttendanceForDate': 'No attendance record for this date',
    'attendanceSummary': 'Attendance summary',
    'attendanceDetails': 'Attendance details',
    'fees': 'Fees',
    'lessons': 'Lessons',
    'messages': 'Messages',
    'settings': 'Settings',
    'manageTeaching': 'Your teaching, at a glance',
    'todayFocus': 'Today’s focus',
    'quickActions': 'Quick actions',
    'recentActivity': 'Recent activity',
    'viewAll': 'View all',
    'totalStudents': 'Total students',
    'activeBatches': 'Active batches',
    'pendingFees': 'Pending fees',
    'attendanceToday': 'Attendance today',
    'onboarding1Title': 'Keep every student in view',
    'onboarding1Body':
        'Organize profiles, batches, and parent details in one calm workspace.',
    'onboarding2Title': 'Stay ahead of the month',
    'onboarding2Body': 'Track attendance, fees, and lesson plans without the spreadsheet shuffle.',
    'onboarding3Title': 'Built for your routine',
    'onboarding3Body': 'Use English or Bangla, choose your theme, and keep a local backup in your control.',
    'skip': 'Skip',
    'next': 'Next',
    'getStarted': 'Get started',
    'appearance': 'Appearance',
    'language': 'Language',
    'theme': 'Theme',
    'backupRestore': 'Backup & restore',
    'subscription': 'Premium features',
    'about': 'About',
    'light': 'Light',
    'dark': 'Dark',
    'english': 'English',
    'bangla': 'বাংলা',
    'backupTitle': 'Your data stays close',
    'backupBody': 'Export a portable backup whenever you need peace of mind.',
    'backupNow': 'Back up now',
    'restoreBackup': 'Restore backup',
    'backupSuccess': 'Backup saved successfully',
    'restoreSuccess': 'Backup restored successfully',
    'comingSoon': 'Coming next in your build sequence',
    'comingSoonBody': 'The foundation is ready. This module will grow into a focused workspace for your daily teaching flow.',
    'addStudent': 'Add student',
    'addBatch': 'Add batch',
    'startMarking': 'Start marking',
    'recordPayment': 'Record payment',
    'planLesson': 'Plan a lesson',
    'messageParent': 'Message a parent',
    'openBackup': 'Open backup',
    'noRecentActivity': 'No recent activity yet',
    'noRecentActivityBody':
        'Add your first student or batch to make this dashboard yours.',
    'aboutBody': 'LinguaLens is a local-first teaching companion. Account sync and Google login are reserved for a future release.',
    'version': 'Version 0.1.0',
    'changeLanguage': 'Change language',
    'chooseTheme': 'Choose your theme',
    'premiumTitle': 'A little more room to grow',
    'premiumBody': 'Premium architecture is ready for future features such as reports, cloud sync, and advanced templates.',
    'plannedFeatures': 'Planned features',
    'unlimitedStudents': 'Unlimited students',
    'advancedReports': 'Advanced reports',
    'cloudSync': 'Cloud sync',
    'allStudents': 'All',
    'activeStudents': 'Active',
    'archivedStudents': 'Archived',
    'noStudentsYet': 'No Students Yet',
    'tapToAddFirstStudent': 'Tap the + button to add your first student.',
    'noResultsFound': 'No Results Found',
    'tryDifferentSearch': 'Try different search terms.',
    'studentCode': 'Student code',
    'parentName': 'Parent name',
    'parentPhone': 'Parent phone',
    'fullName': 'Full name',
    'phone': 'Phone',
    'schoolName': 'School name',
    'className': 'Class / grade',
    'address': 'Address',
    'notes': 'Notes',
    'takePhoto': 'Take photo',
    'chooseFromGallery': 'Choose from gallery',
    'removePhoto': 'Remove photo',
    'whatsappParent': 'WhatsApp parent',
    'smsParent': 'SMS parent',
    'batchesEnrolled': 'Batches enrolled',
    'feeSummary': 'Fee summary',
    'editStudent': 'Edit student',
    'deleteStudent': 'Delete student',
    'deleteStudentConfirm': 'This will permanently delete this student and related records. This cannot be undone.',
    'archiveStudent': 'Archive student',
    'archiveStudentConfirm':
        'The student will be marked as inactive. You can restore them later.',
    'restoreStudent': 'Restore student',
    'studentDeleted': 'Student deleted',
    'studentArchived': 'Student archived',
    'studentRestored': 'Student restored',
    'studentSaved': 'Student saved',
    'save': 'Save',
    'cancel': 'Cancel',
    'required': 'Required',
    'studentDetails': 'Student details',
    'searchStudents': 'Search students',
    'noParentInfo': 'No parent information yet',
    'active': 'Active',
    'archived': 'Archived',
    'addFirstStudent': 'Add your first student',
    'studentCount': 'students',
    'noBatchesYet': 'No batches yet',
    'noBatchesEnrolled': 'No batches enrolled',
    'noFeeRecords': 'No fee records',
    'noAttendanceRecords': 'No attendance records',
    'studentNotFound': 'Student not found',
    'retry': 'Retry',
    'errorMessage': 'Something went wrong. Please try again.',
    'saveStudent': 'Save student',
    'photoPermission': 'Photo access is needed to choose a student photo.',
    'searchStudentsHint': 'Search by name, code, parent, or phone',
    'filter': 'Filter',
    'createBatch': 'Create batch',
    'editBatch': 'Edit batch',
    'batchName': 'Batch name',
    'subject': 'Subject',
    'schedule': 'Schedule',
    'defaultMonthlyFee': 'Default monthly fee',
    'batchColor': 'Batch color',
    'createFirstBatch': 'Create your first batch',
    'noBatchesFound': 'No batches found',
    'enrolledStudents': 'Enrolled students',
    'enrollStudent': 'Enroll student',
    'joiningDate': 'Joining date',
    'customFee': 'Custom fee',
    'leaveEmptyForDefault': 'Leave empty to use the batch default',
    'removedFromBatch': 'Student removed from batch',
    'removeFromBatch': 'Remove from batch',
    'removeFromBatchConfirm': 'Remove this student from the batch?',
    'batchDeleted': 'Batch deleted',
    'batchArchived': 'Batch archived',
    'batchRestored': 'Batch restored',
    'batchSaved': 'Batch saved',
    'studentEnrolled': 'Student enrolled',
    'studentAlreadyEnrolled': 'Student is already enrolled in this batch',
    'noStudentsToEnroll': 'No students available to enroll',
    'allBatchesEnrolled': 'All active students are already enrolled',
    'feeOverview': 'Fee overview',
    'lessonPlans': 'Lesson plans',
    'enrollmentNote': 'Enrollment note',
    'viewFees': 'View fees',
    'addLesson': 'Add lesson',
    'perMonth': '/month',
    'searchBatches': 'Search batches',
    'noStudentsEnrolled': 'No students enrolled yet',
    'batchDetails': 'Batch details',
    'batchNotFound': 'Batch not found',
    'description': 'Description',
    'saveBatch': 'Save batch',
    'subjectHint': 'Choose or type a subject',
    'scheduleHint': 'e.g. Saturday, Monday, Wednesday — 8:00 AM to 9:30 AM',
    'enrollDateHint': 'Select a joining date',
    'selectStudent': 'Select a student',
    'studentAvailable': 'Available',
    'enrolled': 'Enrolled',
    'selectStudentToContinue': 'Select a student to continue',
    'batchStatus': 'Batch status',
    'created': 'Created',
    'noLessonPlans': 'No lesson plans yet',
    'noFeeOverview': 'Fee tracking will appear here',
    'confirmDeleteBatch':
        'This will permanently delete the batch and its enrollment records.',
    'batchActive': 'Active',
    'batchArchivedStatus': 'Archived',
    'feeDashboard': 'Fee dashboard',
    'monthlyFees': 'Monthly fees',
    'totalFee': 'Total fee',
    'collected': 'Collected',
    'due': 'Due',
    'totalCollected': 'Total collected',
    'totalDue': 'Total due',
    'totalPaid': 'Total paid',
    'remainingDue': 'Remaining due',
    'assigned': 'Assigned',
    'discount': 'Discount',
    'finalFee': 'Final fee',
    'dueAmount': 'Due amount',
    'unpaid': 'Unpaid',
    'partial': 'Partial',
    'paid': 'Paid',
    'cash': 'Cash',
    'bankTransfer': 'Bank transfer',
    'mobileBanking': 'Mobile banking',
    'other': 'Other',
    'paymentMethod': 'Payment method',
    'paymentDate': 'Payment date',
    'paymentNote': 'Payment note',
    'paymentNoteHint': 'Optional note about this payment',
    'amount': 'Amount',
    'amountRequired': 'Enter an amount greater than zero',
    'collectPayment': 'Collect payment',
    'savePayment': 'Save payment',
    'savingPayment': 'Saving payment…',
    'paymentSaved': 'Payment saved',
    'deletePayment': 'Delete payment',
    'deletePaymentConfirm':
        'Delete this payment entry? The fee balance will be recalculated.',
    'paymentDeleted': 'Payment deleted',
    'paymentHistory': 'Payment history',
    'recentPayments': 'Recent payments',
    'noRecentPayments': 'No payments recorded recently',
    'overdue': 'Overdue',
    'noOverdue': 'No overdue fees. You are all caught up.',
    'noFeeHistory': 'No fee history yet',
    'noFeeRecordsThisMonth': 'No fee records this month',
    'generateFeesToCreate':
        'Generate monthly fees for active enrollments to see them here.',
    'generateFees': 'Generate fees',
    'generationSettings': 'Generation settings',
    'generationExplanation': 'Only active students enrolled on or before the selected month are included. Existing records are safely skipped.',
    'feeMonth': 'Fee month',
    'newFees': 'New fee records',
    'alreadyGenerated': 'Already generated',
    'newFee': 'New',
    'exists': 'Exists',
    'generating': 'Generating…',
    'feesGenerated': 'Fees generated',
    'noEligibleFeeStudents': 'No eligible students',
    'addStudentsToBatchFirst':
        'Add active students to a batch before generating fees.',
    'viewBatches': 'View batches',
    'selectMonth': 'Select month',
    'selectBatch': 'Select batch',
    'allBatches': 'All batches',
    'futurePaymentDate': 'Payment date cannot be in the future',
    'january': 'January',
    'february': 'February',
    'march': 'March',
    'april': 'April',
    'may': 'May',
    'june': 'June',
    'july': 'July',
    'august': 'August',
    'september': 'September',
    'october': 'October',
    'november': 'November',
    'december': 'December',
  };

  static const _bn = <String, String>{
    'appName': 'লিঙ্গুয়ালেন্স',
    'appTagline': 'পড়ানোর আরও সহজ উপায়',
    'welcome': 'স্বাগতম, শিক্ষক',
    'dashboard': 'ড্যাশবোর্ড',
    'students': 'শিক্ষার্থী',
    'batches': 'ব্যাচ',
    'attendance': 'উপস্থিতি',
    'today': 'আজ',
    'previousDay': 'আগের দিন',
    'nextDay': 'পরের দিন',
    'markAttendance': 'উপস্থিতি নিন',
    'saveAttendance': 'উপস্থিতি সংরক্ষণ',
    'attendanceSaved': 'উপস্থিতি সংরক্ষিত হয়েছে',
    'attendanceCalendar': 'উপস্থিতির ক্যালেন্ডার',
    'attendanceNote': 'উপস্থিতির নোট',
    'saveNote': 'নোট সংরক্ষণ',
    'clearNote': 'নোট মুছুন',
    'present': 'উপস্থিত',
    'absent': 'অনুপস্থিত',
    'late': 'দেরি',
    'leave': 'ছুটি',
    'unmarked': 'নেওয়া হয়নি',
    'expected': 'প্রত্যাশিত',
    'marked': 'নেওয়া হয়েছে',
    'noActiveBatches': 'কোনো সক্রিয় ব্যাচ নেই',
    'createBatchToMarkAttendance':
        'উপস্থিতি নিতে একটি ব্যাচ তৈরি করে শিক্ষার্থী ভর্তি করুন',
    'noEligibleStudents': 'এই তারিখে যোগ্য কোনো শিক্ষার্থী নেই',
    'noStudentsForAttendance': 'উপস্থিতির জন্য কোনো শিক্ষার্থী নেই',
    'enrollStudentsFirst': 'প্রথমে এই ব্যাচে শিক্ষার্থী ভর্তি করুন',
    'markAllPresent': 'সবাইকে উপস্থিত করুন',
    'clearAll': 'সব মুছুন',
    'archivedBatchInfo': 'এই ব্যাচটি আর্কাইভ করা',
    'noAttendanceRecordsYet': 'এখনও কোনো উপস্থিতি রেকর্ড নেই',
    'attendanceWillAppear': 'উপস্থিতি নেওয়ার পর এখানে দেখা যাবে',
    'noAttendanceForDate': 'এই তারিখে কোনো উপস্থিতির রেকর্ড নেই',
    'attendanceSummary': 'উপস্থিতির সারাংশ',
    'attendanceDetails': 'উপস্থিতির তথ্য',
    'fees': 'ফি',
    'lessons': 'পাঠ পরিকল্পনা',
    'messages': 'বার্তা',
    'settings': 'সেটিংস',
    'manageTeaching': 'আপনার পড়ানো, এক নজরে',
    'todayFocus': 'আজকের ফোকাস',
    'quickActions': 'দ্রুত কাজ',
    'recentActivity': 'সাম্প্রতিক কার্যক্রম',
    'viewAll': 'সব দেখুন',
    'totalStudents': 'মোট শিক্ষার্থী',
    'activeBatches': 'সক্রিয় ব্যাচ',
    'pendingFees': 'বকেয়া ফি',
    'attendanceToday': 'আজকের উপস্থিতি',
    'onboarding1Title': 'প্রতিটি শিক্ষার্থীকে কাছে রাখুন',
    'onboarding1Body': 'প্রোফাইল, ব্যাচ এবং অভিভাবকের তথ্য এক জায়গায় গোছান।',
    'onboarding2Title': 'মাসের হিসাব সহজ রাখুন',
    'onboarding2Body':
        'স্প্রেডশিট ছাড়াই উপস্থিতি, ফি এবং পাঠ পরিকল্পনা দেখুন।',
    'onboarding3Title': 'আপনার রুটিনের জন্য তৈরি',
    'onboarding3Body':
        'বাংলা বা ইংরেজি বেছে নিন, থিম বদলান, আর নিজের স্থানীয় ব্যাকআপ রাখুন।',
    'skip': 'এড়িয়ে যান',
    'next': 'পরবর্তী',
    'getStarted': 'শুরু করুন',
    'appearance': 'দেখতে কেমন হবে',
    'language': 'ভাষা',
    'theme': 'থিম',
    'backupRestore': 'ব্যাকআপ ও পুনরুদ্ধার',
    'subscription': 'প্রিমিয়াম ফিচার',
    'about': 'অ্যাপ সম্পর্কে',
    'light': 'লাইট',
    'dark': 'ডার্ক',
    'english': 'English',
    'bangla': 'বাংলা',
    'backupTitle': 'আপনার ডেটা আপনার কাছেই',
    'backupBody': 'নির্ভরতার জন্য যেকোনো সময় একটি ব্যাকআপ নিন।',
    'backupNow': 'ব্যাকআপ নিন',
    'restoreBackup': 'ব্যাকআপ ফিরিয়ে আনুন',
    'backupSuccess': 'ব্যাকআপ সফলভাবে সংরক্ষিত হয়েছে',
    'restoreSuccess': 'ব্যাকআপ সফলভাবে ফিরিয়ে আনা হয়েছে',
    'comingSoon': 'আপনার বিল্ড সিকোয়েন্সে শিগগিরই আসছে',
    'comingSoonBody': 'ভিত্তি প্রস্তুত। এই মডিউলটি আপনার দৈনন্দিন পড়ানোর কাজে আরও ফোকাসড হবে।',
    'addStudent': 'শিক্ষার্থী যোগ করুন',
    'addBatch': 'ব্যাচ যোগ করুন',
    'startMarking': 'উপস্থিতি নিন',
    'recordPayment': 'পেমেন্ট লিখুন',
    'planLesson': 'পাঠ পরিকল্পনা',
    'messageParent': 'অভিভাবককে বার্তা',
    'openBackup': 'ব্যাকআপ খুলুন',
    'noRecentActivity': 'এখনও কোনো কার্যক্রম নেই',
    'noRecentActivityBody':
        'প্রথম শিক্ষার্থী বা ব্যাচ যোগ করলে ড্যাশবোর্ডটি আপনার হয়ে উঠবে।',
    'aboutBody': 'লিঙ্গুয়ালেন্স একটি লোকাল-ফার্স্ট টিচিং কমপ্যানিয়ন। অ্যাকাউন্ট সিঙ্ক ও গুগল লগইন ভবিষ্যৎ সংস্করণের জন্য রাখা হয়েছে।',
    'version': 'সংস্করণ ০.১.০',
    'changeLanguage': 'ভাষা বদলান',
    'chooseTheme': 'আপনার থিম বেছে নিন',
    'premiumTitle': 'আরও বড় হওয়ার জায়গা',
    'premiumBody': 'রিপোর্ট, ক্লাউড সিঙ্ক এবং উন্নত টেমপ্লেটের মতো ফিচারের জন্য প্রিমিয়াম আর্কিটেকচার প্রস্তুত।',
    'plannedFeatures': 'পরিকল্পিত ফিচার',
    'unlimitedStudents': 'সীমাহীন শিক্ষার্থী',
    'advancedReports': 'উন্নত রিপোর্ট',
    'cloudSync': 'ক্লাউড সিঙ্ক',
    'allStudents': 'সব',
    'activeStudents': 'সক্রিয়',
    'archivedStudents': 'আর্কাইভ করা',
    'noStudentsYet': 'এখনও কোনো শিক্ষার্থী নেই',
    'tapToAddFirstStudent': 'প্রথম শিক্ষার্থী যোগ করতে + বোতামে চাপুন।',
    'noResultsFound': 'কোনো ফলাফল নেই',
    'tryDifferentSearch': 'অন্যভাবে খুঁজে দেখুন।',
    'studentCode': 'শিক্ষার্থী কোড',
    'parentName': 'অভিভাবকের নাম',
    'parentPhone': 'অভিভাবকের ফোন',
    'fullName': 'পুরো নাম',
    'phone': 'ফোন',
    'schoolName': 'স্কুলের নাম',
    'className': 'শ্রেণি / গ্রেড',
    'address': 'ঠিকানা',
    'notes': 'নোট',
    'takePhoto': 'ছবি তুলুন',
    'chooseFromGallery': 'গ্যালারি থেকে নিন',
    'removePhoto': 'ছবি সরান',
    'whatsappParent': 'হোয়াটসঅ্যাপে অভিভাবক',
    'smsParent': 'এসএমএস অভিভাবককে',
    'batchesEnrolled': 'ভর্তি হওয়া ব্যাচ',
    'feeSummary': 'ফি সারাংশ',
    'editStudent': 'শিক্ষার্থী সম্পাদনা',
    'deleteStudent': 'শিক্ষার্থী মুছুন',
    'deleteStudentConfirm': 'এই শিক্ষার্থী ও সম্পর্কিত তথ্য স্থায়ীভাবে মুছে যাবে। এটি আর ফেরানো যাবে না।',
    'archiveStudent': 'শিক্ষার্থী আর্কাইভ করুন',
    'archiveStudentConfirm':
        'শিক্ষার্থীকে নিষ্ক্রিয় হিসেবে রাখা হবে। পরে আবার চালু করতে পারবেন।',
    'restoreStudent': 'শিক্ষার্থী ফিরিয়ে আনুন',
    'studentDeleted': 'শিক্ষার্থী মুছে ফেলা হয়েছে',
    'studentArchived': 'শিক্ষার্থী আর্কাইভ করা হয়েছে',
    'studentRestored': 'শিক্ষার্থী ফিরিয়ে আনা হয়েছে',
    'studentSaved': 'শিক্ষার্থী সংরক্ষিত হয়েছে',
    'save': 'সংরক্ষণ',
    'cancel': 'বাতিল',
    'required': 'প্রয়োজনীয়',
    'studentDetails': 'শিক্ষার্থীর তথ্য',
    'searchStudents': 'শিক্ষার্থী খুঁজুন',
    'noParentInfo': 'এখনও অভিভাবকের তথ্য নেই',
    'active': 'সক্রিয়',
    'archived': 'আর্কাইভ করা',
    'addFirstStudent': 'প্রথম শিক্ষার্থী যোগ করুন',
    'studentCount': 'জন শিক্ষার্থী',
    'noBatchesYet': 'এখনও কোনো ব্যাচ নেই',
    'noBatchesEnrolled': 'কোনো ব্যাচে ভর্তি নেই',
    'noFeeRecords': 'কোনো ফি রেকর্ড নেই',
    'noAttendanceRecords': 'কোনো উপস্থিতি রেকর্ড নেই',
    'studentNotFound': 'শিক্ষার্থী পাওয়া যায়নি',
    'retry': 'আবার চেষ্টা',
    'errorMessage': 'কিছু ভুল হয়েছে। আবার চেষ্টা করুন।',
    'saveStudent': 'শিক্ষার্থী সংরক্ষণ',
    'photoPermission': 'শিক্ষার্থীর ছবি বাছাই করতে ছবির অনুমতি দরকার।',
    'searchStudentsHint': 'নাম, কোড, অভিভাবক বা ফোন দিয়ে খুঁজুন',
    'filter': 'ফিল্টার',
    'createBatch': 'ব্যাচ তৈরি করুন',
    'editBatch': 'ব্যাচ সম্পাদনা',
    'batchName': 'ব্যাচের নাম',
    'subject': 'বিষয়',
    'schedule': 'সময়সূচি',
    'defaultMonthlyFee': 'ডিফল্ট মাসিক ফি',
    'batchColor': 'ব্যাচের রং',
    'createFirstBatch': 'প্রথম ব্যাচ তৈরি করুন',
    'noBatchesFound': 'কোনো ব্যাচ পাওয়া যায়নি',
    'enrolledStudents': 'ভর্তি হওয়া শিক্ষার্থী',
    'enrollStudent': 'শিক্ষার্থী ভর্তি করুন',
    'joiningDate': 'ভর্তির তারিখ',
    'customFee': 'কাস্টম ফি',
    'leaveEmptyForDefault': 'ডিফল্ট ফি ব্যবহার করতে খালি রাখুন',
    'removedFromBatch': 'শিক্ষার্থী ব্যাচ থেকে সরানো হয়েছে',
    'removeFromBatch': 'ব্যাচ থেকে সরান',
    'removeFromBatchConfirm': 'এই শিক্ষার্থীকে ব্যাচ থেকে সরাবেন?',
    'batchDeleted': 'ব্যাচ মুছে ফেলা হয়েছে',
    'batchArchived': 'ব্যাচ আর্কাইভ করা হয়েছে',
    'batchRestored': 'ব্যাচ ফিরিয়ে আনা হয়েছে',
    'batchSaved': 'ব্যাচ সংরক্ষিত হয়েছে',
    'studentEnrolled': 'শিক্ষার্থী ভর্তি হয়েছে',
    'studentAlreadyEnrolled': 'শিক্ষার্থী ইতোমধ্যে এই ব্যাচে ভর্তি আছে',
    'noStudentsToEnroll': 'ভর্তির জন্য কোনো শিক্ষার্থী নেই',
    'allBatchesEnrolled': 'সব সক্রিয় শিক্ষার্থী ইতোমধ্যে ভর্তি',
    'feeOverview': 'ফি সারাংশ',
    'lessonPlans': 'পাঠ পরিকল্পনা',
    'enrollmentNote': 'ভর্তির নোট',
    'viewFees': 'ফি দেখুন',
    'addLesson': 'পাঠ যোগ করুন',
    'perMonth': '/মাস',
    'searchBatches': 'ব্যাচ খুঁজুন',
    'noStudentsEnrolled': 'এখনও কোনো শিক্ষার্থী ভর্তি নেই',
    'batchDetails': 'ব্যাচের তথ্য',
    'batchNotFound': 'ব্যাচ পাওয়া যায়নি',
    'description': 'বিবরণ',
    'saveBatch': 'ব্যাচ সংরক্ষণ',
    'subjectHint': 'বিষয় বেছে নিন বা লিখুন',
    'scheduleHint': 'যেমন: শনি, সোম, বুধ — সকাল ৮টা থেকে ৯টা ৩০',
    'enrollDateHint': 'ভর্তির তারিখ বেছে নিন',
    'selectStudent': 'শিক্ষার্থী বেছে নিন',
    'studentAvailable': 'উপলব্ধ',
    'enrolled': 'ভর্তি আছে',
    'selectStudentToContinue': 'চালিয়ে যেতে শিক্ষার্থী বেছে নিন',
    'batchStatus': 'ব্যাচের অবস্থা',
    'created': 'তৈরি হয়েছে',
    'noLessonPlans': 'এখনও কোনো পাঠ পরিকল্পনা নেই',
    'noFeeOverview': 'ফি ট্র্যাকিং এখানে দেখা যাবে',
    'confirmDeleteBatch': 'এতে ব্যাচ ও এর ভর্তি রেকর্ড স্থায়ীভাবে মুছে যাবে।',
    'batchActive': 'সক্রিয়',
    'batchArchivedStatus': 'আর্কাইভ করা',
    'feeDashboard': 'ফি ড্যাশবোর্ড',
    'monthlyFees': 'মাসিক ফি',
    'totalFee': 'মোট ফি',
    'collected': 'আদায় হয়েছে',
    'due': 'বকেয়া',
    'totalCollected': 'মোট আদায়',
    'totalDue': 'মোট বকেয়া',
    'totalPaid': 'মোট পরিশোধ',
    'remainingDue': 'অবশিষ্ট বকেয়া',
    'assigned': 'নির্ধারিত',
    'discount': 'ছাড়',
    'finalFee': 'চূড়ান্ত ফি',
    'dueAmount': 'বকেয়ার পরিমাণ',
    'unpaid': 'পরিশোধ হয়নি',
    'partial': 'আংশিক',
    'paid': 'পরিশোধিত',
    'cash': 'নগদ',
    'bankTransfer': 'ব্যাংক ট্রান্সফার',
    'mobileBanking': 'মোবাইল ব্যাংকিং',
    'other': 'অন্যান্য',
    'paymentMethod': 'পেমেন্টের মাধ্যম',
    'paymentDate': 'পেমেন্টের তারিখ',
    'paymentNote': 'পেমেন্ট নোট',
    'paymentNoteHint': 'এই পেমেন্ট সম্পর্কে ঐচ্ছিক নোট',
    'amount': 'পরিমাণ',
    'amountRequired': 'শূন্যের বেশি পরিমাণ লিখুন',
    'collectPayment': 'পেমেন্ট নিন',
    'savePayment': 'পেমেন্ট সংরক্ষণ',
    'savingPayment': 'সংরক্ষণ হচ্ছে…',
    'paymentSaved': 'পেমেন্ট সংরক্ষিত হয়েছে',
    'deletePayment': 'পেমেন্ট মুছুন',
    'deletePaymentConfirm':
        'এই পেমেন্টটি মুছবেন? ফি ব্যালেন্স নতুন করে হিসাব হবে।',
    'paymentDeleted': 'পেমেন্ট মুছে ফেলা হয়েছে',
    'paymentHistory': 'পেমেন্টের ইতিহাস',
    'recentPayments': 'সাম্প্রতিক পেমেন্ট',
    'noRecentPayments': 'সাম্প্রতিক কোনো পেমেন্ট নেই',
    'overdue': 'মেয়াদোত্তীর্ণ বকেয়া',
    'noOverdue': 'কোনো মেয়াদোত্তীর্ণ বকেয়া নেই। সব হিসাব ঠিক আছে।',
    'noFeeHistory': 'এখনও কোনো ফি ইতিহাস নেই',
    'noFeeRecordsThisMonth': 'এই মাসে কোনো ফি রেকর্ড নেই',
    'generateFeesToCreate':
        'এখানে দেখতে সক্রিয় ভর্তি শিক্ষার্থীদের জন্য মাসিক ফি তৈরি করুন।',
    'generateFees': 'ফি তৈরি করুন',
    'generationSettings': 'তৈরির সেটিংস',
    'generationExplanation': 'নির্বাচিত মাসের আগে বা সেই মাসে ভর্তি থাকা সক্রিয় শিক্ষার্থীদেরই ধরা হবে। আগে তৈরি রেকর্ড নিরাপদে বাদ যাবে।',
    'feeMonth': 'ফির মাস',
    'newFees': 'নতুন ফি রেকর্ড',
    'alreadyGenerated': 'আগেই তৈরি',
    'newFee': 'নতুন',
    'exists': 'আছে',
    'generating': 'তৈরি হচ্ছে…',
    'feesGenerated': 'ফি তৈরি হয়েছে',
    'noEligibleFeeStudents': 'যোগ্য কোনো শিক্ষার্থী নেই',
    'addStudentsToBatchFirst':
        'ফি তৈরির আগে ব্যাচে সক্রিয় শিক্ষার্থী যোগ করুন।',
    'viewBatches': 'ব্যাচ দেখুন',
    'selectMonth': 'মাস বেছে নিন',
    'selectBatch': 'ব্যাচ বেছে নিন',
    'allBatches': 'সব ব্যাচ',
    'futurePaymentDate': 'পেমেন্টের তারিখ ভবিষ্যতের হতে পারবে না',
    'january': 'জানুয়ারি',
    'february': 'ফেব্রুয়ারি',
    'march': 'মার্চ',
    'april': 'এপ্রিল',
    'may': 'মে',
    'june': 'জুন',
    'july': 'জুলাই',
    'august': 'আগস্ট',
    'september': 'সেপ্টেম্বর',
    'october': 'অক্টোবর',
    'november': 'নভেম্বর',
    'december': 'ডিসেম্বর',
  };

  String t(String key) => (locale.languageCode == 'bn' ? _bn : _en)[key] ?? key;
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'bn'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}

extension LocalizationX on BuildContext {
  AppLocalizations get l10n =>
      Localizations.of<AppLocalizations>(this, AppLocalizations) ??
      AppLocalizations(const Locale('en'));
}
